import { getPosts, getPost } from "../../utils/helper";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

const formatDate = (date) => {
  var hours = date.getHours();
  var minutes = date.getMinutes();
  var ampm = hours >= 12 ? "PM" : "AM";
  hours = hours % 12;
  hours = hours ? hours : 12; // the hour "0" should be "12"
  minutes = minutes < 10 ? "0" + minutes : minutes;
  var strTime = hours + ":" + minutes + " " + ampm;
  return (
    date.getDate() +
    "/" +
    new Intl.DateTimeFormat("en", { month: "short" }).format(date) +
    "/" +
    date.getFullYear() +
    " " +
    strTime
  );
};
export const getStaticPaths = async () => {
  const posts = await getPosts();
  return {
    // if path doesn't exist, false forwards to 404
    fallback: false,
    // paths is an array of the paths forwarded to component
    paths: posts.blogPostCollection.items.map((post) => ({
      params: { slug: post.slug },
    })),
  };
};
export const getStaticProps = async (context) => {
  const data = await getPost(context.params.slug);

  console.log(data.blogPostCollection.items[0]);

  return {
    props: {
      data: { data: data.blogPostCollection.items[0] },
    },
  };
};

export default function Post({ data }) {
  console.log(data.data);
  return (
    <div className={styles.container}>
      <Head>
        <title>My Simple Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{data.data.title}</h1>
        <p className="styles.description">{data.data.date}</p>

        <p className={styles.description}>Hey</p>
        {console.log(data.data.body.json)}
        <div className="body">
          {documentToReactComponents(data.data.body.json)}
        </div>

        {/* <div className={styles.grid}>
          {console.log(posts)}
          {posts.blogPostCollection.items.map((post) => (
            <a
              key={post.slug}
              href="https://nextjs.org/docs"
              className={styles.card}
            >
              <h2>{post.title}</h2>
              <p>{post.excerpt}</p>
            </a>
          ))}
        </div> */}

        {data.data.imagesCollection.items.map((img) => (
          <Image
            key={img.url}
            alt={img.title}
            height={img.height}
            width={img.width}
            src={img.url}
          />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
