// Make sure you import the GraphQL Client first. I had an error until I moved it to first.
// import { GraphQLClient, gql } from "graphql-request";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { getPosts } from "../utils/helper";

export const getStaticProps = async () => {
  // const endpoint = `https://graphql.contentful.com/content/v1/spaces/${process.env.SPACE_ID}`;

  // const graphQLClient = new GraphQLClient(endpoint, {
  //   headers: {
  //     authorization: `Bearer ${process.env.ACCESS_TOKEN}`,
  //   },
  // });
  // const postsQuery = gql`
  //   {
  //     blogPostCollection {
  //       items {
  //         title
  //         excerpt
  //         date
  //         body {
  //           json
  //         }
  //       }
  //     }
  //   }
  // `;

  const posts = await getPosts();

  return {
    props: { posts },
  };
};

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>A Simple Blog Site</h1>

        <p className={styles.description}>
          Nothing fancy... Just a little bit of Contentful and Next.js
        </p>

        <div className={styles.grid}>
          {console.log(posts.blogPostCollection.items)}
          {posts.blogPostCollection.items.map((post) => (
            <Link
              key={post.slug}
              href={`/posts/${post.slug}`}
              className={styles.card}
            >
              <a>
                <h2>{post.title}</h2>
                <p>{post.excerpt}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
